name: First WorkFlow
on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
      
jobs:
   example-job:
    runs-on: ubuntu-latest
    steps:
     - name: print welcome message
       run: echo  "Welcome message for first workflow"
       
     - name: checkout repristory
       uses: actions/checkout@v4.2.2

     - name: Set up JDK 21
       uses: actions/setup-java@v4
       with:
         java-version: '21'
         distribution: 'temurin'

     - name: Test With Maven
       run: mvn test
       
